services:
  - type: web
    name: book-search-engine
    runtime: node
    plan: free
    buildCommand: cd server && npm install && npm run build && cd ../client && npm install && npm run build && cp -r dist ../server/dist/
    startCommand: cd server && node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # This will be set manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true # This will auto-generate a secure key
